apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-svc
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - host:
        - kubernetes-playground.schul-cloud.org
      secretName: kubernetes-playground-schul-cloud-org
  rules:
    - host: kubernetes-playground.schul-cloud.org
      http:
        paths:
          - path: /
            backend:
              serviceName: client-clusterip-service
              servicePort: 3000
          - path: /api/
            backend:
              serviceName: server-clusterip-service
              servicePort: 5000

